### ISSUE TITLE
Can't find input directory

### ISSUE THREAD

**Issue by emilhaegglund** [rderelle/Broccoli#1]
Hey, trying to run the first step of the pipeline and it can't find the input directory, it looks like all / are removed from the directory path.
```
python broccoli.py -step 1 -threads 28 -dir /data/emil/proteomes/ -ext .faa

            Broccoli v1.0


 --- STEP 1: kmer clustering

 # parameters
 proteomes dir : ./dataemilproteomes/
 kmer size     : 100
 min size seq  : 10
 min nb aa     : 15

 # check input files
ERROR STEP 1: the directory ' ./dataemilproteomes/ ' does not exist.
```
Best regards,
Emil

**Comment by rderelle** [comment]
Hi Emil,

thanks. I have fixed this bug.
Please download the new version (v1.01) and give it a try.

I will later release a new version of Broccoli, Windows compatible, that better handle paths and filenames.
