### ISSUE TITLE
Discarted proteins

### ISSUE THREAD

**Issue by V-JJ** [rderelle/Broccoli#18]
Hi!

It would be great if Broccoli could generate a fasta file with proteins that are not used in the final analysis. That is, the discarted subset of data.

Thanks,
Vadim

**Comment by rderelle** [comment]
Hi Vadim,

Thanks for the suggestion. May I ask what do you mean by "proteins that are not used in the final analysis"?

Are you referring to the proteins set aside after the k-mer filtering step (step 1)? If so, they are re-injected into the final classification during the last step.

Romain

**Comment by V-JJ** [comment]
Hi!

No, I was talking about all those proteins that are not organized in orthogroups (OGs).
For example, let's say that we have 1000 input proteins. 900 will be grouped in OGs. This is the final result.

The remaining 100 proteins (let's call them singletons) are not listed anywhere (if I'm not wrong). I just suggested that it would be useful to have a list of them or a separate FASTA file.

Thanks,
V

**Comment by rderelle** [comment]
Thanks Vadim. That makes sense and it shouldn't be difficult to implement.
I'll do it next week.

Romain

**Comment by V-JJ** [comment]
Thank you!

**Comment by xvazquezc** [comment]
Sorry for commenting in a closed issue. I'm also interested in this but I haven't seen any commit related to this.

**Comment by rderelle** [comment]
Now implemented in v1.3: step3 generates an output file 'unclassified_proteins.txt'

My apologies for this delay.
Romain

**Comment by V-JJ** [comment]
Great! Thank you :)

Vadim
