### ISSUE TITLE
How to visualize the results? 

### ISSUE THREAD

**Issue by Diamonds95** [rderelle/Broccoli#2]
I run the pipline smoothly and get some results, but I don't know how to display! I tried the Cytoscape and Gephi to open the /dir_step3/OGs_in_network.txt but failed, and it's seemd that this file is not a readable text file. Is there any suggestion? Thanks for reply !

**Comment by rderelle** [comment]
Hi,

Broccoli creates and analyses an 'orthology network', but does not output it.
The file '/dir_step3/OGs_in_network.txt' is a list of OGs, i.e. the list of node communities, with custom names, not a network.

You could try to open the file /dir_step4/orthologous_pairs.txt with Cytoscape. But this file only contains a **subset** of the initial network.
May I ask you why you need to have access to the full network ?

nb: the network usually contains millions of edges ... it is quite difficult to visualise it.

Romain

**Comment by Diamonds95** [comment]
Thanks for your reply! Actually I try to find the OGs list in network, but I can not open the file '/dir_step3/OGs_in_network.txt' correctly, so I thought may be it must be opend by a specific software.
