### ISSUE TITLE
Python errors

### ISSUE THREAD

**Issue by fmarletaz** [rderelle/Broccoli#3]
hi - thanks for developing Broccoli, sounds like a great tool! I am trying to run it (for the first time) on a set of 25 metazoan genomes and I am encountering some errors. Basically, it looks like it is stuck at the stage 2.  I tried to run manually the commands that failed (`diamond blastp --quiet --threads 1 - ...`), I got this error: `No such file or directory  Error: Error opening file ./dir_step2/0.db`

The error log: 
```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/f/fmarletaz/work/miniconda2/envs/broccoli/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/f/fmarletaz/work/miniconda2/envs/broccoli/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/work/RokhsarU/ferdi/Broccoli/scripts/broccoli_step2.py", line 216, in process_file
    subprocess.check_output(path_diamond + ' blastp --quiet --threads 1 --db ./dir_step2/' + file_db.replace('.fas','.db') + ' --max-target-seqs ' + str(max_per_species) + ' --query ./dir_step1/' + file + ' \
  File "/home/f/fmarletaz/work/miniconda2/envs/broccoli/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/f/fmarletaz/work/miniconda2/envs/broccoli/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'diamond blastp --quiet --threads 1 --db ./dir_step2/0.db --max-target-seqs 6 --query ./dir_step1/10.fas                  --compress 1 --more-sensitive -e 0.001 -o ./dir_step2/10/10_0.gz --outfmt 6 qseqid sseqid qstart qend qseq_gapped sseq_gapped 2>&1' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "broccoli.py", line 157, in <module>
    broccoli_step2.step2_phylomes(evalue, max_per_species, path_diamond, path_fasttree, trim_thres, nb_threads)
  File "/work/RokhsarU/ferdi/Broccoli/scripts/broccoli_step2.py", line 67, in step2_phylomes
    multithread_process_file(list_files, nb_threads)
  File "/work/RokhsarU/ferdi/Broccoli/scripts/broccoli_step2.py", line 141, in multithread_process_file
    results_2 = tmp_res.get()
  File "/home/f/fmarletaz/work/miniconda2/envs/broccoli/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
subprocess.CalledProcessError: Command 'diamond blastp --quiet --threads 1 --db ./dir_step2/0.db --max-target-seqs 6 --query ./dir_step1/10.fas                  --compress 1 --more-sensitive -e 0.001 -o ./dir_step2/10/10_0.gz --outfmt 6 qseqid sseqid qstart qend qseq_gapped sseq_gapped 2>&1' returned non-zero exit status 1.
slurmstepd: error: *** JOB 7967016 ON sango40406 CANCELLED AT 2020-02-08T17:07:52 ***
```

**Comment by rderelle** [comment]
Hi,

Are you sure you are using the correct version of DIAMOND ?
It should be version 0.9.25 or above.

Romain

**Comment by fmarletaz** [comment]
Hi,
Thanks. I installed everything with condo, diamond is v0.9.30.131, so it
should not be a problem. I also ran the example dataset successfully.

Ferdi

**Comment by rderelle** [comment]
Hi Ferdinand,

my apologies, I have actually misread your first message: Diamond is not running correctly because it cannot find the file ./dir_step2/0.db, which corresponds to the Diamond database of the species '0' of your dataset. I'm afraid I have never seen this kind of issue.

Could you please try the following command (modify the path of your diamond executable):

diamond makedb --in ./dir_step1/0.fas --db ./dir_step2/0.db
 
You should get an error message since Diamond failed to create the file ./dir_step2/0.db.
Could you please post it here?

thanks
Romain

**Comment by fmarletaz** [comment]
Salut, 
Ok, so I investigated a bit further and I realised it was my fault: a few of my proteomes had problematic characters ('.' and '*' which are sometimes added as stop in some pipelines) and diamond really doesn't like them!

**Comment by rderelle** [comment]
Hi Ferdi,

many thanks for pointing this problem.
I'll do some testing and add a filter to Broccoli.

Romain

**Comment by fmarletaz** [comment]
Hi Romain,

By the way, I have actually a naive question. One of the reasons OMA is
really convenient for phylogenomics is that it reports an ‘orthologous
matrix’ where is easy given some taxonomic rules to pick single-copy genes
shared by a set of species for phylogenetic or genomic analysis. From what
I saw, Broccoli reports both orthogroups and pairwise orthologues, but not
such a matrix, is there a workaround? Maybe I am missing something!

Thanks!

Ferdi


On February 20, 2020 at 18:32:10, romain derelle (notifications@github.com)
wrote:

Hi Ferdi,

many thanks for pointing this problem.
I'll do some testing and add a filter to Broccoli.

Romain

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rderelle/Broccoli/issues/3?email_source=notifications&email_token=AAIMSXJLLDEBEGJKV4QNFEDRDZEZTA5CNFSM4KRZCWKKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMMQ7UQ#issuecomment-588845010>,
or unsubscribe

**Comment by rderelle** [comment]
yes, you are right regarding the absence of matrix/table in the outputs.
I'll upload soon a version of Broccoli that creates such matrix at the end of step 3.

thanks
Romain
